-- MySQL Script generated by MySQL Workbench
-- Sat Apr 15 13:11:54 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Mission_Set`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mission_Set` (
  `Mission_ID` INT NOT NULL,
  `Misson_Name` VARCHAR(45) NULL,
  `Mission_Type` VARCHAR(45) NULL,
  `Mission_Status` VARCHAR(45) NULL,
  `Num_Of_Objectives` VARCHAR(45) NULL,
  `Point_Value` VARCHAR(45) NULL,
  `Time_Started` DATETIME NULL,
  `Time_Completed` DATETIME NULL,
  PRIMARY KEY (`Mission_ID`),
  UNIQUE INDEX `Mission_ID_UNIQUE` (`Mission_ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Objective`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Objective` (
  `Objective_ID` INT NOT NULL,
  `Objective_Name` VARCHAR(45) NULL,
  `Objective_Type` VARCHAR(45) NULL,
  `Time_Started` DATETIME NULL,
  `Time_Completed` DATETIME NULL,
  `Point_Value` VARCHAR(45) NULL,
  `Obejtive_Status` VARCHAR(45) NULL,
  `Mission_ID` INT NOT NULL,
  PRIMARY KEY (`Objective_ID`, `Mission_ID`),
  UNIQUE INDEX `ObjID_UNIQUE` (`Objective_ID` ASC),
  INDEX `fk_Objective_Mission_Set_idx` (`Mission_ID` ASC),
  CONSTRAINT `fk_Objective_Mission_Set`
    FOREIGN KEY (`Mission_ID`)
    REFERENCES `mydb`.`Mission_Set` (`Mission_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Attack`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Attack` (
  `Attack_ID` INT NOT NULL,
  `Attack_Name` VARCHAR(45) NULL,
  `Attack_Type` VARCHAR(45) NULL,
  `Time_Started` VARCHAR(45) NULL,
  `Time_Completed` VARCHAR(45) NULL,
  `Attack_Status` VARCHAR(45) NULL,
  `Attack_Result` VARCHAR(45) NULL,
  `Objective_ID` INT NOT NULL,
  `Mission_ID` INT NOT NULL,
  PRIMARY KEY (`Attack_ID`, `Objective_ID`, `Mission_ID`),
  UNIQUE INDEX `Attack_ID_UNIQUE` (`Attack_ID` ASC),
  INDEX `fk_Attack_Objective1_idx` (`Objective_ID` ASC, `Mission_ID` ASC),
  CONSTRAINT `fk_Attack_Objective1`
    FOREIGN KEY (`Objective_ID` , `Mission_ID`)
    REFERENCES `mydb`.`Objective` (`Objective_ID` , `Mission_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
